[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn -c gunicorn.conf.py app:app"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[environments.production]
FLASK_ENV = "production"